### ISSUE TITLE
Some issues on Debian Buster (10.1)

### ISSUE THREAD

**Issue by simonvizzini** [TheReal1604/disk-encryption-hetzner#20]
I followed the Debian Guide (SWRAID-1 LVM LUKS) and encountered some issue.

**Problem 1:**

After restoring the vg config I got this message about different sector sizes:
````
Device /dev/mapper/cryptroot has size of 7812687488 sectors which is smaller than corresponding PV size of 7812720256 sectors. Was device resized?
````

I was able to solve this by simply deleting the volume group again and re-creating everything from scratch instead of restoring the backup:

````
vgremove vg0
lvcreate -n home -L100G vg0
lvcreate -n root -L300G vg0
lvcreate -n swap -L32G vg0
````

**Problem 2:**

`update-grub` hangs and shows no output at all. I debugged this by using `strace -f update-grub`
This did show a problem:
````
[pid 15012] openat(AT_FDCWD, "/run/udev/data/b1:0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
````
Solution was to also mount /run before chroot'ing:

````
mount --bind /run /mnt/run
````

**Problem 3:**

`update-grub` now run executes successfully, but the resulting config has an empty `root=` parameter. Thus after SSH'ing into dropbear and unlocking the cryptroot nothing happened, because grub wasn't able to continue boot. The offending menu entry in grub.cfg looks like

````
'gnulinux-5.0.21-2-pve-advanced-826c461f-7527-4f81-8899-2752ff825c7c' {
                load_video
                insmod gzio
                if [ x$grub_platform = xxen ]; then insmod xzio; insmod lzopio; fi
                insmod part_gpt
                insmod part_gpt
                insmod diskfilter
                insmod mdraid1x
                insmod ext2
                set root='mduuid/2d47ce5ebb51653216be521ba6329c11'
                if [ x$feature_platform_search_hint = xy ]; then
                  search --no-floppy --fs-uuid --set=root --hint='mduuid/2d47ce5ebb51653216be521ba6329c11'  2c07da8f-e0d8-4dca-b772-df4e7c2fc250
                else
                  search --no-floppy --fs-uuid --set=root 2c07da8f-e0d8-4dca-b772-df4e7c2fc250
                fi
                echo    'Loading Linux 5.0.21-2-pve ...'
                linux   /vmlinuz-5.0.21-2-pve root= ro  nomodeset consoleblank=0
                echo    'Loading initial ramdisk ...'
                initrd  /initrd.img-5.0.21-2-pve
        }
````

Notice that the root parameter on this line is empty: `linux   /vmlinuz-5.0.21-2-pve root= ro  nomodeset consoleblank=0`

This is where I'm stuck now. I was able to to temporary fix it by simpy manually editing `/boot/grub/grub.cfg` and adding `/dev/vg0/root` as root argument. But this will obviously get overwritten on the next `grub-update`. I really dislike grub and I don't know how to make it autodetect. I've spent the last few hours searching for a solution, but grub is such a complex behemoth....

Any ideas/help would be greatly appreciated.

**Comment by aidanhs** [comment]
Some comments on problem 1 (had the same issue on Ubuntu 18.04):

It relates to https://github.com/TheReal1604/disk-encryption-hetzner/issues/9

I also had to fix it by recreating the volume groups. Specifically in my case:
```
vgcreate vg0 /dev/mapper/cryptroot
lvcreate -n swap -L16G vg0
lvcreate -n root -l100%FREE vg0
```
(I note the comment above doesn't mention vgcreate?)

Intuitively, I'm kinda surprised it ever worked without altering the vg config - surely cryptsetup needs a slice of the disk to store its own machinery (e.g. the actual key), in which case the encrypted disk is a little smaller?

**Comment by razorness** [comment]
Installed successfully with Debian Buster. 
I had an additional HDD in spare, so I gone with LVM-Management instead of `rsync`.
Requirment is using  lvm group.

My setup:
- nvme ssd raid1 `md0` for `/boot`
- nvme ssd raid1 `md1` with vgroup `vg0` for `swap` and `/`, which I wanted to get encrypted
- hhd `sda` in spare (for temporary tasks)

### Move Volumes to other disk
- add partition to spare disk via `fdisk` to `sda`
- create a new physical device for lvm: `pvcreate /dev/sda1`
- extend vgroup to `sda1`: `vgextend vg0 /dev/sda1`
- move volumes to `sda1`: 
  - `pvmove -n /dev/vg0/swap /dev/md1 /dev/sda1`
  - `pvmove -n /dev/vg0/root /dev/md1 /dev/sda1`
- reduce vgroup: `vgreduce vg0 /dev/md1` 

### Encrypt your raid partition
- cleanup file system `wipefs /dev/md1`
- create encrypted device: `cryptsetup luksFormat -c aes-xts-plain64 -s 512 /dev/md1` 
- open encrypted device: `cryptsetup luksOpen /dev/md1 cryptroot`

### Move Volumes to encrypted disk
- create a new phyicial device for lvm: `pvcreate /dev/mapper/cryptroot`
- extend vgroup to `sda1`: `vgextend vg0 /dev/mapper/cryptroot`
- move volumes to `/dev/mapper/cryptroot`: 
  - `pvmove -n /dev/vg0/swap /dev/sda1 /dev/mapper/cryptroot`
  - `pvmove -n /dev/vg0/root /dev/sda1 /dev/mapper/cryptroot`
- reduce vgroup: `vgreduce vg0 /dev/sda1` 

Then you go ahead with mounting all that to `/mnt`, `chroot`, editing `/etc/crypttab` etc..

This way looked very clean to me . You don't touch any data in volumes. No rsync.

If you don't have a disk in spare, you should be able to remove a disk from raid array and use it as temporary device.

**Comment by BloodyNora** [comment]
semi-successfully followed the guide on debian 10.3 just seconds ago. 

-> in the resulting `chroot` of the old setup in hetzners rescue system, i needed to apply changes to the lvm config as outlined in https://bbs.archlinux.org/viewtopic.php?pid=1513816#p1513816 - otherwise accessing the LVs wouldn't be possible, thus i couldn't progress past the `update-grub` command.

thank you for the guide!

**Comment by leviwheatcroft** [comment]
@razorness @BloodyNora would either of you be able to submit a PR with these updates?  It's been forever since I wrote the debian guide and to be honest I'm not really certain I could include your changes correctly because I don't really remember the process.

Having the guide has really helped a bunch of people, but if we just leave updates here in the issues it makes it really difficult for others to follow.

**Comment by TheReal1604** [comment]
Merged the PR. Thanks guys!
